### ISSUE TITLE
Fancyhdr 4.3 broke package mdframed

### ISSUE THREAD

**Issue by Witiko** [pietvo/fancyhdr#18] opened 2024-07-22 16:14 UTC
Last week's update to fancyhdr 4.3 in commit https://github.com/pietvo/fancyhdr/commit/2ab42eea683fcd4f28f8485b4a6f0c7952a73582 broke the interaction between fancyhdr and and mdframed.

Here is a minimal working example:

``` tex
\documentclass{article}
\RequirePackage{fancyhdr,mdframed}
\pagestyle{fancy}
\cfoot{\begin{mdframed}foo\end{mdframed}}
\begin{document}
bar
\end{document}
```

After the last week's update, compiling this document with pdfLaTeX produces the following error:

```
! LaTeX Error: Something's wrong--perhaps a missing \item.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.7 \end{document}
                  
?
```

**Comment by pietvo** [comment] 2024-07-23 07:28
Actually, the same problem occurs with other environments that are based on `trivlist`, e.g. `center`.

`\cfoot{\begin{center}foo\end{center}}` gives the same error message. I'm looking for a solution that still solves the other problem.

**Comment by pietvo** [comment] 2024-07-23 10:02
Quick fix:

In this piece of code:

```
  \newcommand\f@nch@resetpar{%
    \f@nch@everypar{}%
    \cs_set_eq:NN \everypar\tex_everypar:D
    \cs_set_eq:NN \par     \tex_par:D
    \cs_set_eq:NN \@@par   \tex_par:D
    \cs_set_eq:NN \endgraf \tex_par:D
  }
```
the third line (`\cs_set_eq:NN \everypar\tex_everypar:D`) has been added.
I'll prepare a new release, and the new version will be in this repository shortly.

**Closed by pietvo** 2024-07-23 10:02 UTC

**Comment by FrankMittelbach** [comment] 2024-07-23 20:42
I think for a shortterm fix that is probably fine, but I don't think it is the way it should be. This is a hard overwrite of an internal mechanism and either there should be an interface in the paragraph mechanism to encapsulate such a change or there should be a different approach but not a low-level overwrite. I suspect the latter (ie a different approach eventually) but that will have to wait until we are further advanced in handling  hooks in different contexts (which is really what is the problem here). So this note is mainly saying that this needs revisiting at some point in the future.

**Comment by pietvo** [comment] 2024-07-23 20:59
@FrankMittelbach Absolutely. But I don't have another mechanism at the moment, and I can't allow the paragraph hooks from the main text be activated in `fancyhdr`. I hope you developers will come up with a mechanism to reset the paragraph hooks locally in a group,  (i.e. without affecting the outside world).

**Comment by FrankMittelbach** [comment] 2024-07-24 06:54
quite correct, As I said a context-dependent behavior is missing, so for now it is the best you can do.

**Comment by FrankMittelbach** [comment] 2024-11-27 22:52
> What do you think about this (still temporary) fix??

worth trying I would say. I'm sorry that we aren't faster with all the things we want to do  (see how long it took for me to get back to the missing support in multicol) but yes, as a temporary fix this is probably as good as it can get.

**Comment by FrankMittelbach** [comment] 2024-11-27 22:54
However, having said that I'm a bit surprised in what the cause is that the paragraph hooks cause trouble for you ... but in all honsty I don't have the time right now to look at that in earnest.

**Comment by pietvo** [comment] 2024-11-28 12:33
> However, having said that I'm a bit surprised in what the cause is that the paragraph hooks cause trouble for you ... but in all honsty I don't have the time right now to look at that in earnest.

Someone used a paragraph hook to solve a problem with theorem labels when `hyperref` was used. If the theorem crossed a page boundary, or was about to cross it, the paragraph hook could end up in `fancyhdr` instead of the theorem. Anyway, paragraph hooks meant for the main text shouldn't end up in `fancyhdr`. Neither should other ones, but I haven't met another one yet.

See https://github.com/latex3/hyperref/issues/294
